apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus          # referenced by uid in dashboard.json
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: '5s'   # matches prometheus scrape_interval
